### ISSUE TITLE
Not able to pass output from earlier step as text

### ISSUE THREAD

**Issue by richa-p** [aliencube/microsoft-teams-actions#14]
Hello,

I'm trying to read a file and then send it in Text section but it's not working. Here is the sample: 

- name: Read scan results summary
        id: scan-results
        run: |
          SAST_SUMMARY=$(cat sast-summary.txt)
          echo "::set-output name=SAST_SUMMARY::${SAST_SUMMARY}"
- name: Send a message to Microsoft Teams
        if: ${{ steps.pipeline-scan.outcome == 'failure' }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{env.WEBHOOK_URI}}
          title: 'Veracode Pipeline Scan found vulnerabilities in ${{ env.REPOSITORY_NAME }}'
          summary: 'Flaws Summary: '
          text: 'Flaws text: ${{steps.scan-results.outputs.SAST_SUMMARY}}'
          theme_color: a72828
          actions: '[{ "@type": "OpenUri", "name": "View Results", "targets": [{ "os": "default", "uri": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }] }]'

Am I missing anything? Or this is not supported with the current version?

**Comment by riker09** [comment]
Is this the content of your YAML file?

```yaml
jobs:
  your-job:
    runs-on: ubuntu-latest
    steps:
    - name: Read scan results summary
      id: scan-results
      run: |
        SAST_SUMMARY=$(cat sast-summary.txt)
        echo "::set-output name=SAST_SUMMARY::${SAST_SUMMARY}"
    - name: Send a message to Microsoft Teams
      if: ${{ steps.pipeline-scan.outcome == 'failure' }}
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{env.WEBHOOK_URI}}
        title: 'Veracode Pipeline Scan found vulnerabilities in ${{ env.REPOSITORY_NAME }}'
        summary: 'Flaws Summary: '
        text: 'Flaws text: ${{steps.scan-results.outputs.SAST_SUMMARY}}'
        theme_color: a72828
        actions: '[{ "@type": "OpenUri", "name": "View Results", "targets": [{ "os": "default", "uri": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }] }]'
```

(I have added the `jobs` to `steps` paragraphs)

Do you get any errors? 

From my experience the workflow files are pretty fragile when it comes to single and double quotes. If your output `SAST_SUMMARY` contains single quotes this might break the second step since `text` is also single-quote-escaped.
