### ISSUE TITLE
Action broken?

### ISSUE THREAD

**Issue by heathsnow** [aliencube/microsoft-teams-actions#16]
When I attempt to use this action with the minimum configuration Teams just displays empty text:

Config
-------

```yml
      - name: 'Teams notify started'
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.teams_webhook_url }}
          summary: "Deployment started."
```
Result
------

<img width="752" alt="Screen Shot 2022-02-01 at 4 46 27 PM" src="https://user-images.githubusercontent.com/1410607/152075393-196e9b69-86af-46d6-8dd8-d2cb1da415a7.png">
