### ISSUE TITLE
Escape Quotes in fields

### ISSUE THREAD

**Issue by dkershner6** [aliencube/microsoft-teams-actions#21]
The action breaks without having JSON unfriendly characters escaped, and GitHub actions doesn't have a way to do this to the input (but C# does!).

Can the inputs please be escaped before sending?

**Comment by maikschneider** [comment]
Yes, this is a really annoying issue. Are there any plans to fix this?

**Comment by maikschneider** [comment]
Ah, there was a simple solution: Just escape the input via `toJSON()` function. The returned value is in quotes, so you need to remove them in the schema, e.g.:

```
    steps:
      - uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          title: 'New comment on issue #${{ github.event.issue.number }}: "${{ github.event.issue.title }}"'
          sections: '[{ "activityText": ${{ toJSON(github.event.comment.body) }}  }]'
```
