### ISSUE TITLE
Not a Valid Version String

### ISSUE THREAD

**Issue by gallowaystorm** [aliencube/microsoft-teams-actions#22]
We keep getting the error:

/usr/share/dotnet/sdk/3.1.423/NuGet.targets(128,5): error : 'v1.1.18' is not a valid version string. (Parameter 'value') [/app/GitHubActionsTeams.sln]

Not sure how to fix it as that is a valid version string that Github accepts...

```
      - name: Send Release Notes to MS Teams
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: <some url>
          title: 'Release Notes for ${{ env.VERSION }}'
          summary: '${{ env.GITHUB_SERVER_URL}}/${{ env.GITHUB_REPOSITORY }}/blob/main/CHANGELOG.md'
          text: 'This is some text'
          theme_color: green
```
